### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by darkclouder** [fyrelab/sentri#1]
# Planned improvements
- [ ]  Redesign and restructure config loader
- [ ]  Add TLS support for firebase module
- [ ]  Replace GPL dependencies
- [ ]  Clean Makefiles
